export default {
  ADD_PRODUCT_NAVIGATION: "Add Product Nav",
  ADD_BANK_PAGE: "Add Bank Record",
  ADD_PRODUCT_PAGE: "Add Product",
  ADD_STORE_PAGE: "Add Store",
  AUTH_NAVIGATION: "Auth",
  BALANCE_PAGE: "Balance",
  LOGIN_PAGE: "Login",
  HOME_NAVIGATION: "Home Nav",
  HOME_PAGE: "Home",
  ORDER_DETAIL_PAGE: "Order Details",
  ORDERS_LIST_PAGE: "Orders List",
  PRODUCT_DETAIL_PAGE: "Product Details",
  PRODUCTS_PAGE: "Market",
  PRODUCTS_NAVIGATION: "Products",
  PROFILE_PAGE: "Profile",
  SIGN_UP_PAGE: "Sign Up",
  STORE_PAGE: "Store",
  UPDATE_PROFILE_PAGE: "Update Profile",
  WELCOME_PAGE: "Welcome",
  WITHDRAWAL_PAGE: "Withdraw",
};
